services:
  backend:
    container_name: pwd-validator-api
    build: ./backend
    restart: always
    ports:
      - 3000:3000

  frontend:
    container_name: pwd-validator-app
    build: ./frontend
    restart: always
    ports:
      - 80:80