version: '1.0'

services:
  backend:
    container_name: pwd-validator-api
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    container_name: pwd-validator-app
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
